// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh-CM_8IRY1ju9lqxmaZUcUWtNYhd1br4',
    appId: '1:717603748085:web:3ee8e84a36f1d1bf492dbc',
    messagingSenderId: '717603748085',
    projectId: 'batrek-e1b3c',
    authDomain: 'batrek-e1b3c.firebaseapp.com',
    storageBucket: 'batrek-e1b3c.appspot.com',
    measurementId: 'G-089B8PLPMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGuhPmLchzeKqQNGVaigr_VS_2ZUGzdjY',
    appId: '1:717603748085:android:7ed312a477a2755d492dbc',
    messagingSenderId: '717603748085',
    projectId: 'batrek-e1b3c',
    storageBucket: 'batrek-e1b3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFtGc4nDT82qLiI7tpl7h3__e3VdYc99g',
    appId: '1:717603748085:ios:ee9e19ece3a9aca5492dbc',
    messagingSenderId: '717603748085',
    projectId: 'batrek-e1b3c',
    storageBucket: 'batrek-e1b3c.appspot.com',
    iosBundleId: 'com.example.socialMobilapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFtGc4nDT82qLiI7tpl7h3__e3VdYc99g',
    appId: '1:717603748085:ios:f9a24681d07111c5492dbc',
    messagingSenderId: '717603748085',
    projectId: 'batrek-e1b3c',
    storageBucket: 'batrek-e1b3c.appspot.com',
    iosBundleId: 'com.example.socialMobilapp.RunnerTests',
  );
}
